apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-net6-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-net6-api
  template:
    metadata:
      labels:
         app: sample-net6-api
    spec:
      containers:
        - name: sample-net6-api
          image: public.ecr.aws/mock-node-api/lowsandbox:sample-net6-api
          env:
            - name: ENV
              value: "Unclassified"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000

